const data = [

    {
        "account":12345,
        "name":"Tim",
        "location":"Arizona",
        "age":25
    },
    {
        "account":12346,
        "name":"Tom",
        "location":"Texas",
        "age":32
    },
    {
        "account":12347,
        "name":"Sarah",
        "location":"California",
        "age":31
    },
    {
        "account":12348,
        "name":"Bob",
        "location":"Nevada",
        "age":27
    },
    {
        "account":12349,
        "name":"Bill",
        "location":"Arizona",
        "age":31
    },
    {
        "account":12350,
        "name":"Alex",
        "location":"Nevada",
        "age":31
    },
    {
        "account":12351,
        "name":"Alice",
        "location":"California",
        "age":40
    },
    {
        "account":12352,
        "name":"Eric",
        "location":"Nevada",
        "age":45
    },
    {
        "account":12353,
        "name":"Errin",
        "location":"California",
        "age":49
    },
    {
        "account":12354,
        "name":"Kyle",
        "location":"Arizona",
        "age":25
    },
    {
        "account":12355,
        "name":"Karren",
        "location":"California",
        "age":45
    },
    {
        "account":12356,
        "name":"Joe",
        "location":"California",
        "age":34
    },
    {
        "account":12357,
        "name":"Julie",
        "location":"Arizona",
        "age":62
    },
    {
        "account":12358,
        "name":"Marco",
        "location":"Nevada",
        "age":47
    }
];


module.exports = data;