const data = [

    {
        "name":"Car-1",
        "color":"red",
        "year":1965
    },
    {
        "name":"Car-2",
        "color":"black",
        "year":1966
    },
    {
        "name":"Car-3",
        "color":"green",
        "year":1967
    },
    {
        "name":"Car-4",
        "color":"red",
        "year":1965
    },
    {
        "name":"Car-5",
        "color":"blue",
        "year":1966
    },
    {
        "name":"Car-6",
        "color":"green",
        "year":1967
    },
    {
        "name":"Car-7",
        "color":"white",
        "year":1965
    },
    {
        "name":"Car-1",
        "color":"black",
        "year":1966
    },
    {
        "name":"Car-9",
        "color":"green",
        "year":1967
    },
    {
        "name":"Car-10",
        "color":"black",
        "year":1965
    },
    {
        "name":"Car-11",
        "color":"red",
        "year":1966
    },
    {
        "name":"Car-12",
        "color":"blue",
        "year":1967
    },
    {
        "name":"Car-13",
        "color":"red",
        "year":1965
    },
    {
        "name":"Car-14",
        "color":"blue",
        "year":1966
    },
    {
        "name":"Car-15",
        "color":"white",
        "year":1967
    },
    {
        "name":"Car-16",
        "color":"green",
        "year":1965
    },
    {
        "name":"Car-17",
        "color":"red",
        "year":1966
    },
    {
        "name":"Car-18",
        "color":"white",
        "year":1967
    },
    {
        "name":"Car-19",
        "color":"green",
        "year":1965
    },
    {
        "name":"Car-20",
        "color":"blue",
        "year":1966
    },
    {
        "name":"Car-21",
        "color":"red",
        "year":1967
    },
    {
        "name":"Car-22",
        "color":"red",
        "year":1965
    },
    {
        "name":"Car-23",
        "color":"blue",
        "year":1966
    },
    {
        "name":"Car-24",
        "color":"black",
        "year":1967
    },
    {
        "name":"Car-25",
        "color":"green",
        "year":1965
    },
    {
        "name":"Car-26",
        "color":"blue",
        "year":1965
    },
    {
        "name":"Car-27",
        "color":"green",
        "year":1966
    },
    {
        "name":"Car-28",
        "color":"white",
        "year":1966
    },
    {
        "name":"Car-28",
        "color":"black",
        "year":1965
    },
    {
        "name":"Car-29",
        "color":"black",
        "year":1967
    },
    {
        "name":"Car-30",
        "color":"black",
        "year":1967
    }
];


module.exports = data;